"""Alembic environment configuration for async migrations."""

import asyncio
import re
from logging.config import fileConfig
from pathlib import Path

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

from app.core.config import settings
from app.db.session import Base

# Register all models for autogenerate support
from app.db.models.user import User  # noqa: F401
from app.db.models.preferences import UserPreferences  # noqa: F401
from app.db.models.gamification import UserGamification  # noqa: F401
from app.db.models.template import UserTemplate  # noqa: F401

config = context.config
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


# ── Django-style sequential revision numbering ────────────────────────────────

def get_next_revision_number() -> str:
    """Generate Django-style sequential revision number (0001, 0002, etc.)."""
    versions_dir = Path(__file__).parent / "versions"

    if not versions_dir.exists():
        return "0001"

    existing_numbers = []
    for file in versions_dir.glob("*.py"):
        match = re.match(r'^(\d{4})_', file.name)
        if match:
            existing_numbers.append(int(match.group(1)))

    if not existing_numbers:
        return "0001"

    return f"{max(existing_numbers) + 1:04d}"


def generate_slug_from_operations(upgrade_ops) -> str:
    """Generate a descriptive slug from autogenerated migration operations."""
    if not upgrade_ops or not upgrade_ops.ops:
        return "auto"

    actions = []
    for op in upgrade_ops.ops:
        op_type = type(op).__name__

        if op_type == "CreateTableOp":
            actions.append(f"create_{op.table_name}")
        elif op_type == "DropTableOp":
            actions.append(f"drop_{op.table_name}")
        elif op_type == "AddColumnOp":
            actions.append(f"add_{op.column_name}_to_{op.table_name}")
        elif op_type == "DropColumnOp":
            actions.append(f"drop_{op.column_name}_from_{op.table_name}")
        elif op_type == "AlterColumnOp":
            actions.append(f"alter_{op.column_name}_in_{op.table_name}")
        elif op_type == "CreateIndexOp":
            actions.append(f"add_index_{op.index_name}")
        elif op_type == "DropIndexOp":
            actions.append(f"drop_index_{op.index_name}")
        elif op_type == "ModifyTableOps":
            for nested_op in op.ops:
                nested_type = type(nested_op).__name__
                if nested_type == "AddColumnOp":
                    actions.append(f"add_{nested_op.column_name}_to_{op.table_name}")
                elif nested_type == "DropColumnOp":
                    actions.append(f"drop_{nested_op.column_name}_from_{op.table_name}")
                elif nested_type == "AlterColumnOp":
                    actions.append(f"alter_{nested_op.column_name}_in_{op.table_name}")

    if not actions:
        return "auto"

    slug = "_".join(actions[:3])
    if len(actions) > 3:
        slug += "_and_more"

    slug = re.sub(r'[^a-z0-9_]', '_', slug.lower())
    slug = re.sub(r'_+', '_', slug).strip('_')
    return slug[:50] if len(slug) > 50 else slug


def process_revision_directives(_context, _revision, directives):
    """Replace random hash with sequential number and auto-generate slug."""
    if directives:
        for directive in directives:
            if hasattr(directive, 'rev_id'):
                directive.rev_id = get_next_revision_number()

            if hasattr(directive, 'upgrade_ops') and directive.upgrade_ops:
                if not directive.message or directive.message.strip() == "":
                    directive.message = generate_slug_from_operations(directive.upgrade_ops)


# ── Migration runners ─────────────────────────────────────────────────────────

def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        process_revision_directives=process_revision_directives,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        render_as_batch=True,  # required for SQLite ALTER TABLE support
        process_revision_directives=process_revision_directives,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
